### ISSUE TITLE
Card Block Reducing LHS

### ISSUE THREAD

**Issue by hparwani2** [adobecom/milo#917]
Because of the removal of the 'picture' tag in cards.js (https://github.com/adobecom/milo/blob/13885f9b07463a55448c7ff7746f85bc03d890e1/libs/blocks/card/card.js#L155) LCP and FCP timings are increased, it requires images to be served in nextGen formats like webp or loading should be lazy, which works fine in card-horizontal

My question is, why we are removing the picture tag and appending the background image? or is there any other way to reducing timings for LCP and FCP

<img width="1665" alt="Screenshot 2023-07-03 at 10 40 38 AM" src="https://github.com/adobecom/milo/assets/49381235/4ba2a744-d6fe-4d72-9b00-ebdf9133f7ca">

**Comment by meganthecoder** [comment]
In order to match this card block with the caas cards (and to not duplicate work), we opted to use the chimera ui stylesheet (added to libs as caas.css). That means we needed to use the same dom structure, and caas cards have a background image rather than a picture tag.

**Comment by sdmcraft** [comment]
[Related slack discussion](https://cq-dev.slack.com/archives/C03B0BUA75E/p1689234237684919)

**Comment by hparwani2** [comment]
live: https://main--dx-portal--adobe.hlx.live/
page: https://main--dx-portal--adobe.hlx.page/
